// Generates docs/ART_PROMPTS.md: one image-generation prompt per fighter and pose, from the character data.
import { writeFileSync } from 'node:fs';
import { ROSTER } from '../src/characters';
import { POSES } from '../src/ui/fighterVisual';

const POSE_DESC: Record<string, string> = {
  idle: 'neutral fighting stance, weapon held ready, weight on the back foot, looking at the opponent',
  walk: 'mid-stride, leaning forward slightly, weapon lowered',
  crouch: 'crouching low, guard up, knees bent',
  jump: 'airborne, knees tucked, weapon drawn back',
  light: 'fast horizontal strike at full extension, torso rotated, weapon (or fist) at the end of the arm',
  heavy: 'huge overhead or wide two-handed strike at full extension, whole body committed, dramatic motion',
  special: 'channeling supernatural energy, free hand open and glowing, weapon raised, aura around the body',
  block: 'defensive guard, arms/weapon crossed in front of the face, braced',
  hit: 'recoiling from a heavy blow, head thrown back, off balance',
  down: 'lying on the ground on the back, defeated, weapon dropped nearby',
  win: 'victory pose, weapon raised high, proud expression, cape/clothes moving in the wind',
};
const STYLE = 'dark cinematic painted illustration, realistic historical portrait style, dramatic rim lighting, rich detail, ' +
  'Latin American independence era, fantasy supernatural touch, full body, character facing RIGHT, feet touching the bottom edge, ' +
  'transparent background (PNG with alpha) or flat removable background, no text, no logo, no watermark';

const out: string[] = [];
out.push('# Art prompts (generated by `npm run art:prompts`)\n');
out.push('See `docs/ART_PIPELINE.md` for the file format. **Tip:** generate `idle` first, then feed it back as the reference image for every other pose so face/costume stay consistent.\n');
for (const c of ROSTER) {
  const a = c.art;
  out.push(`## ${c.name} — \`${c.id}\``);
  out.push(`Look: ${c.title}; ${a.headgear !== 'none' ? a.headgear + ' headgear, ' : ''}${a.hair} hair, ${a.facial !== 'none' ? a.facial + ', ' : ''}${a.cape !== 'none' ? a.cape + ', ' : ''}${a.build} build, weapon: ${a.weapon}. ` +
    `Palette: primary #${a.palette.primary.toString(16).padStart(6, '0')}, secondary #${a.palette.secondary.toString(16).padStart(6, '0')}, accent #${a.palette.accent.toString(16).padStart(6, '0')}, aura #${a.palette.aura.toString(16).padStart(6, '0')}.\n`);
  out.push(`Reference portrait: \`public/assets/portraits/${c.id}.jpg\`\n`);
  for (const p of POSES) {
    out.push(`- **${p}** → \`public/assets/fighters/${c.id}/${p}.png\`\n  \`${c.name}, ${c.title}, ${POSE_DESC[p]}. Same character, costume and face as the reference. ${STYLE}.\``);
  }
  out.push('');
}
writeFileSync(new URL('../docs/ART_PROMPTS.md', import.meta.url).pathname, out.join('\n'));
console.log('wrote docs/ART_PROMPTS.md');
